### ISSUE TITLE
만들고 있었는데...

### ISSUE THREAD

**Issue by pgmrDohan** [Heavyrisem/COVID-Auto_SelfCheck#2]
쳇

**Comment by Heavyrisem** [comment]
![5F345C16-8BEA-48A6-A569-CFCF27D1B54B](https://user-images.githubusercontent.com/46806498/92418815-8ebe7b00-f1a4-11ea-9185-d07bd7b0205e.jpeg)
제 코드가 도움되면 좋겠네요 ^^7

**Comment by pgmrDohan** [comment]
전 이걸 파이썬으로 만들었죠 ^^7
https://pypi.org/project/Selfcheck/1.6.0/
