### ISSUE TITLE
학교 이름 대신 코드 입력

### ISSUE THREAD

**Issue by minikupa** [Heavyrisem/COVID-Auto_SelfCheck#3]
학교 이름을 검색하지 않고 직접 학교 코드를 입력할 수 있게도 해주실 수 있나요?

**Comment by Heavyrisem** [comment]
추가하겠습니다.

**Comment by minikupa** [comment]
넵 감사합니다.

**Comment by Heavyrisem** [comment]
충청남도면.. 학교 코드가 N으로 시작하나요?

**Comment by minikupa** [comment]
저희 학교 코드는 N으로 시작합니다. 근데 전국을 대상으로 만들어 볼 예정이라서요..

**Comment by Heavyrisem** [comment]
전국마다 코드가 다른데 확인해보려고 여쭤봤습니다.
제가 찾은 데이터가 맞나보네요

**Comment by Heavyrisem** [comment]
해당 기능 추가 완료했습니다.
사용방법은 크게 바뀌지 않았습니다. README 참고해주세요

오류가 또 생기면 issue 열어주세요
