### ISSUE TITLE
계속 참여자를 찾을 수 없다고 합니다.

### ISSUE THREAD

**Issue by minikupa** [Heavyrisem/COVID-Auto_SelfCheck#4]
{"err":"입력하신 정보로 참여자를 찾을 수 없습니다.\n확인후 다시 시도해주세요"}란 오류가 나옵니다. 지역이나, 학교, 학교 구분에 다른 문자를 추가하면 학교 또는 지역 등을 찾을 수 없다는 오류가 나는 것을 보니 학교, 지역은 잘 입력한 것 같습니다.

**Comment by pgmrDohan** [comment]
그거 자기지역으로 링크수정해야함....
그거 싫으면 제 코드로 오시오^^7

**Comment by Heavyrisem** [comment]
입력값을 확인해야 오류를 고칠수 있을것 같아요
중요 정보는 살짝 가리고 올려주세요

**Comment by minikupa** [comment]
이름 : ***, 생년월일 : ******, 소속 시 : 충청남도, 학교이름 : 가야곡중학교, 학교 유형 : 중학교입니다.

**Comment by Heavyrisem** [comment]
알겠습니다. 최대한 빠르게 수정하겠습니다

**Comment by Heavyrisem** [comment]
오류 수정해서 npm에 배포했습니다.
1.2.5 버전 확인해주세요

**Comment by Heavyrisem** [comment]
npm 라이브러리 업데이트 했습니다. 1.2.6 에서
서울 선린인터넷고, 경기도 용인 고등학교 에서 테스트 했습니다.
확인하고 알려주세요

**Comment by minikupa** [comment]
이미 자가진단을 했다고 나오네요. 잘 작동하는 것 같습니다. 감사합니다.
