### ISSUE TITLE
교사용 기능 추가 건의

### ISSUE THREAD

**Issue by minikupa** [Heavyrisem/COVID-Auto_SelfCheck#5]
교사용으로 누가 자가진단을 했는지 안했는지 확인할 수 있는 기능을 추가해주실 수 있으시나요?

**Comment by Heavyrisem** [comment]
가능한지 확인해보고 다시 알려드리겠습니다.

**Comment by Heavyrisem** [comment]
요즘 대회도 많아지고 짬내서 개발할 시간이 점점 줄어드네요
이대로 내버려 둬도 되나 싶은 부분도 많구요 (자가진단 매크로에 대한 문제)
원하시는 기능의 추가는 어려울거 같아 보이네요
